[package]
name = "tr"
version = "0.1.0"
authors = ["Daniel Rocco <drocco@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bstr = "0.2.14"


[dev-dependencies]
rstest = "0.6.4"
